DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(90) NOT NULL,
    password VARCHAR(90) NOT NULL,
    userName VARCHAR(90) NOT NULL,
    score INT
);


